/* automatically generated by rust-bindgen */


#![allow(non_snake_case)]


#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct JS_PersistentRooted<c> {
    pub _base: a<__anon_named_type_0>,
    pub _phantom_0: ::std::marker::PhantomData<c>,
}
impl <c> Default for JS_PersistentRooted<c> {
    fn default() -> Self { unsafe { ::std::mem::zeroed() } }
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct a<__anon_named_type_0> {
    pub b: *mut a<__anon_named_type_0>,
}
impl <__anon_named_type_0> Default for a<__anon_named_type_0> {
    fn default() -> Self { unsafe { ::std::mem::zeroed() } }
}
